//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoPlanesCobro
    {
        public EstadoPlanesCobro()
        {
            this.PlanesCobro = new HashSet<PlanesCobro>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<PlanesCobro> PlanesCobro { get; set; }
    }
}
