//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CondominioEntities : DbContext
    {
        public CondominioEntities()
            : base("name=CondominioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AreaComunal> AreaComunal { get; set; }
        public DbSet<EstadoIncidencia> EstadoIncidencia { get; set; }
        public DbSet<EstadoPlanesCobro> EstadoPlanesCobro { get; set; }
        public DbSet<EstadoResidencias> EstadoResidencias { get; set; }
        public DbSet<Incidencias> Incidencias { get; set; }
        public DbSet<Informacion> Informacion { get; set; }
        public DbSet<PlanAsignado> PlanAsignado { get; set; }
        public DbSet<PlanesCobro> PlanesCobro { get; set; }
        public DbSet<Reservaciones> Reservaciones { get; set; }
        public DbSet<Residencias> Residencias { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<RubroCobro> RubroCobro { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
