//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CondominioEntities : DbContext
    {
        public CondominioEntities()
            : base("name=CondominioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreaComunal> AreaComunal { get; set; }
        public virtual DbSet<Estado_EstadoCuenta> Estado_EstadoCuenta { get; set; }
        public virtual DbSet<EstadoIncidencia> EstadoIncidencia { get; set; }
        public virtual DbSet<EstadoResidencias> EstadoResidencias { get; set; }
        public virtual DbSet<Incidencias> Incidencias { get; set; }
        public virtual DbSet<Informacion> Informacion { get; set; }
        public virtual DbSet<PlanesCobro> PlanesCobro { get; set; }
        public virtual DbSet<Reservaciones> Reservaciones { get; set; }
        public virtual DbSet<Residencias> Residencias { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RubroCobro> RubroCobro { get; set; }
        public virtual DbSet<TipoInformacion> TipoInformacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<EstadoCuenta> EstadoCuenta { get; set; }
    }
}
